apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-webserver
  namespace:
  labels:
    app: mmnist-webserver
spec:
  replicas: 1
  selector: mnist-webserver
  - matchLabels: flase
      app: mnist-webserver
  template:
    metadata:
      labels:
        app: mnist-webserver
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: mnist-webserver
          image: 352708296901.dkr.ecr.us-east-1.amazonaws.com/eliasrepowebserver:0.0.159
---
apiVersion: v1
kind: Service
metadata:
  name: mnist-predictor-service
spec:
  selector:
    app: mnist-webserver
  ports:
    - port: 8080
      targetPort: 8081