apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-webserver
  namespace: devops-alfnar-k8s-eliasnm
  labels:
    app: mnist-predictor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnist-predictor
  template:
    metadata:
      labels:
        app: mnist-predictor
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: mnist-predictor
          image: 352708296901.dkr.ecr.us-east-1.amazonaws.com/eliasrepowebserver:0.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: mnist-predictor-service
spec:
  selector:
    app: mnist-predictor
  ports:
    - port: 8080
      targetPort: 8081
